spring.application.name: config-server
server.port: 8889

logging:  
    level:  
       org.springframework.amqp.rabbit.listener: ERROR
       org.springframework.context.support.AbstractApplicationContext: ERROR
       org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor: ERROR
       
# 配置服务注册中心
eureka.client.serviceUrl.defaultZone: http://peer1:1111/eureka/
eureka.client.healthcheck.enabled: true 
eureka.instance: 
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} 
    
# git管理配置
spring.cloud.config.server.git.uri: http://git.oschina.net/didispace/SpringBoot-Learning/
spring.cloud.config.server.git.searchPaths: Chapter9-1-4/config-repo
spring.cloud.config.server.git.username: 115359178@qq.com
spring.cloud.config.server.git.password: caojian328

# 开启本地配置
spring.profiles.active: native



spring.rabbitmq: 
          host: 192.168.199.82
          port: 5672
          username: caojian
          password: caojian328