spring.application.name: eureka-server
server.port: 1112
eureka.instance.hostname: peer2

#eureka.client.register-with-eureka: false
#eureka.client.fetch-registry: false
eureka.client.serviceUrl.defaultZone: http://peer1:1111/eureka/,http://peer3:1113/eureka/

# 设为false，关闭自我保护
eureka.server.enable-self-preservation: false 
# 清理间隔（单位毫秒，默认是60*1000）
eureka.server.eviction-interval-timer-in-ms: 30 