server.port: 2655

eureka.client.serviceUrl.defaultZone: http://peer1:1111/eureka/
eureka.client.healthcheck.enabled: true
eureka.instance:
lease-expiration-duration-in-seconds: 30
lease-renewal-interval-in-seconds: 10
preferIpAddress: true
instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring.application.name: zipkin-server
#zipkin数据保存到数据库中需要进行如下配置
#表示当前程序不使用sleuth
spring.sleuth.enabled: false
#表示zipkin数据存储方式是mysql
zipkin.storage.type: mysql
#数据库脚本创建地址，当有多个是可使用[x]表示集合第几个元素
spring.datasource.schema[0]: classpath:/zipkin.sql
#spring boot数据源配置
spring.datasource.url: jdbc:mysql://localhost:3306/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
spring.datasource.username: root
spring.datasource.password: caojian
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.initialize: true
spring.datasource.continue-on-error: true

spring.rabbitmq:
          host: 192.168.199.82
          port: 5672
          username: caojian
          password: caojian328


spring.cloud.config.profile: test
spring.cloud.config.uri: http://localhost:8889/
spring.cloud.config.discovery.enabled: true
spring.cloud.config.discovery.serviceId: config-server
spring.cloud.config.failFast: false
spring:
  cloud:
    config:
      enabled: true